apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    # external-secrets will create/manage this Kubernetes Secret
    name: demo-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: "/demo/api-token"
  dataFrom:
    # Pull the whole JSON blob and split it into individual keys
    - extract:
        key: "/demo/db-credentials"
